server:
  port: 9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
    
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/product?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 'postgres'
        platform: org.hibernate.dialect.PostgreSQLDialect

    jpa:
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
        generate-ddl: true
        properties:
          hibernate:
            show-sql: true
            ddl-auto: update
            temp:
              use_jdbc_metadata_defaults: false
            jdbc:
              lob:
                non_contextual_creation: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user-auth

